DROP TABLE RESERVATIONS CASCADE CONSTRAINTS;
DROP TABLE STATIONS_CONNECTORS CASCADE CONSTRAINTS;
DROP TABLE RATES CASCADE CONSTRAINTS;
DROP TABLE FAVOURITES CASCADE CONSTRAINTS;
DROP TABLE CONNECTORS CASCADE CONSTRAINTS;
DROP TABLE BRANDS CASCADE CONSTRAINTS;
DROP TABLE AUTOS CASCADE CONSTRAINTS;
DROP TABLE STATIONS CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE ROLES CASCADE CONSTRAINTS;
DROP TABLE STATISTICS CASCADE CONSTRAINTS;

DROP SEQUENCE USERS_SEQUENCE;
DROP SEQUENCE STATIONS_SEQUENCE;
DROP SEQUENCE AUTOS_SEQUENCE;
DROP SEQUENCE BRANDS_SEQUENCE;
DROP SEQUENCE CONNECTORS_SEQUENCE;
DROP SEQUENCE FAVOURITES_SEQUENCE;
DROP SEQUENCE RATES_SEQUENCE;
DROP SEQUENCE STATIONS_CONNECTORS_SEQUENCE;
DROP SEQUENCE RESERVATIONS_SEQUENCE;
DROP SEQUENCE ROLES_SEQUENCE;
DROP SEQUENCE STATISTICS_SEQUENCE;

CREATE SEQUENCE USERS_SEQUENCE START WITH 1 MAXVALUE 9999999;
CREATE SEQUENCE STATIONS_SEQUENCE START WITH 1 MAXVALUE 9999999;
CREATE SEQUENCE AUTOS_SEQUENCE START WITH 1 MAXVALUE 9999999;
CREATE SEQUENCE BRANDS_SEQUENCE START WITH 1 MAXVALUE 9999999;
CREATE SEQUENCE CONNECTORS_SEQUENCE START WITH 1 MAXVALUE 9999999;
CREATE SEQUENCE FAVOURITES_SEQUENCE START WITH 1 MAXVALUE 9999999;
CREATE SEQUENCE RATES_SEQUENCE START WITH 1 MAXVALUE 9999999;
CREATE SEQUENCE STATIONS_CONNECTORS_SEQUENCE START WITH 1 MAXVALUE 9999999;
CREATE SEQUENCE RESERVATIONS_SEQUENCE START WITH 1 MAXVALUE 9999999;
CREATE SEQUENCE ROLES_SEQUENCE START WITH 1 MAXVALUE 9999999;
CREATE SEQUENCE STATISTICS_SEQUENCE START WITH 1 MAXVALUE 9999999;

CREATE TABLE STATISTICS (
    STATISTIC_ID NUMBER(6) DEFAULT STATISTICS_SEQUENCE.NEXTVAL,
    URI VARCHAR(200) NOT NULL,
    OPERATION_TYPE VARCHAR(30) NOT NULL,
    CREATED_AT DATE,
    BUSINESS_OPERATION_NAME VARCHAR(200)
);

CREATE TABLE USERS (
	USER_ID NUMBER(6) DEFAULT USERS_SEQUENCE.NEXTVAL,
	LASTNAME VARCHAR(30) NOT NULL,
	FIRSTNAME VARCHAR(30) NOT NULL,
	MIDNAME VARCHAR(30),
	MAIL VARCHAR(40) NOT NULL,
	PASSWORD VARCHAR(80) NOT NULL,
	AUTO_ID NUMBER(6),
	ROLE_ID NUMBER(6) NOT NULL
);

CREATE TABLE ROLES (
    ROLE_ID NUMBER(6) DEFAULT ROLES_SEQUENCE.NEXTVAL,
    NAME VARCHAR(30) NOT NULL
);

CREATE TABLE STATIONS (
	STATION_ID NUMBER(6) DEFAULT STATIONS_SEQUENCE.NEXTVAL,
	CORDINATES VARCHAR(50),
	RATE NUMBER(2, 1) DEFAULT 0,
	PRICE DECIMAL(4, 2) DEFAULT NULL,
	STATUS VARCHAR(40) NOT NULL
);

CREATE TABLE AUTOS(
	AUTO_ID NUMBER(6) DEFAULT AUTOS_SEQUENCE.NEXTVAL,
	BRAND_ID NUMBER(2) NOT NULL,
	MODEL VARCHAR(15) NOT NULL,
	MAX_CHARGE NUMBER(4),
	CONNECTOR_ID NUMBER(6) NOT NULL
);

CREATE TABLE BRANDS(
    BRAND_ID NUMBER(3) DEFAULT BRANDS_SEQUENCE.NEXTVAL,
    NAME VARCHAR(15)
);

CREATE TABLE CONNECTORS (
	CONNECTOR_ID NUMBER(3) DEFAULT CONNECTORS_SEQUENCE.NEXTVAL,
	TYPE VARCHAR(30),
	AMPERAGE NUMBER(3),
	VOLTAGE NUMBER(3),
    POWER NUMBER(6,3)
);

CREATE TABLE FAVOURITES(
    FAVOURITE_ID NUMBER(6) DEFAULT FAVOURITES_SEQUENCE.NEXTVAL,
    STATION_ID NUMBER(6) NOT NULL,
    USER_ID NUMBER(6) NOT NULL
);

CREATE TABLE RATES (
    RATE_ID NUMBER(6) DEFAULT RATES_SEQUENCE.NEXTVAL,
    STATION_ID NUMBER(6) NOT NULL,
    USER_ID NUMBER(6) NOT NULL,
    RATE NUMBER(2, 1),
    COMMENTARY VARCHAR(100)
);

CREATE TABLE STATIONS_CONNECTORS (
    INNER_ID NUMBER(6) DEFAULT STATIONS_CONNECTORS_SEQUENCE.NEXTVAL,
    STATION_ID NUMBER(6) NOT NULL,
    CONNECTOR_ID NUMBER(6) NOT NULL
);

CREATE TABLE RESERVATIONS (
    RESERVATION_ID NUMBER(6) DEFAULT RESERVATIONS_SEQUENCE.NEXTVAL,
    TIME TIMESTAMP NOT NULL,
    TIME_END TIMESTAMP NOT NULL,
    CODE VARCHAR(32) NOT NULL,
    USER_ID NUMBER(6) NOT NULL,
    STATION_ID NUMBER(6) NOT NULL,
    CREATED_AT DATE NOT NULL
);

ALTER TABLE USERS ADD CONSTRAINT USERS_PK
    PRIMARY KEY (USER_ID);
ALTER TABLE STATISTICS ADD CONSTRAINT STATISTICS_PK
    PRIMARY KEY (STATISTIC_ID);
ALTER TABLE ROLES ADD CONSTRAINT ROLES_PK
    PRIMARY KEY (ROLE_ID);
ALTER TABLE STATIONS ADD CONSTRAINT STATIONS_PK
    PRIMARY KEY (STATION_ID);
ALTER TABLE AUTOS ADD CONSTRAINT AUTOS_PK
    PRIMARY KEY(AUTO_ID);
ALTER TABLE BRANDS ADD CONSTRAINT BRANDS_PK
    PRIMARY KEY (BRAND_ID);
ALTER TABLE CONNECTORS ADD CONSTRAINT CONNECTORS_PK
    PRIMARY KEY(CONNECTOR_ID);
ALTER TABLE FAVOURITES ADD CONSTRAINT FAVOURITES_PK
    PRIMARY KEY (FAVOURITE_ID);
ALTER TABLE RATES ADD CONSTRAINT RATES_PK
    PRIMARY KEY (RATE_ID);
ALTER TABLE STATIONS_CONNECTORS ADD CONSTRAINT STATIONS_CONNECTORS_PK
    PRIMARY KEY (INNER_ID);
ALTER TABLE RESERVATIONS ADD CONSTRAINT RESERVATIONS_PK
    PRIMARY KEY(RESERVATION_ID);
    
ALTER TABLE USERS ADD CONSTRAINT USERS_MAIL_UNIQUE
    UNIQUE(MAIL);
ALTER TABLE ROLES ADD CONSTRAINT ROLES_NAME_UNIQUE
    UNIQUE(NAME);
ALTER TABLE USERS ADD CONSTRAINT USERS_AUTO_ID
    FOREIGN KEY (AUTO_ID) REFERENCES AUTOS
    ON DELETE CASCADE;

ALTER TABLE STATIONS ADD CONSTRAINT STATIONS_PRICE
    CHECK (PRICE >=0);

ALTER TABLE AUTOS ADD CONSTRAINT AUTOS_BRAND_ID
    FOREIGN KEY (BRAND_ID) REFERENCES BRANDS
    ON DELETE CASCADE;
ALTER TABLE USERS ADD CONSTRAINT USERS_ROLE_ID
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES
    ON DELETE CASCADE;
ALTER TABLE AUTOS ADD CONSTRAINT AUTOS_CONNECTOR_ID
    FOREIGN KEY (CONNECTOR_ID) REFERENCES CONNECTORS
    ON DELETE CASCADE;
ALTER TABLE AUTOS ADD CONSTRAINT AUTOS_MAX_CHARGE
    CHECK (MAX_CHARGE >=0);
 
ALTER TABLE BRANDS ADD CONSTRAINT BRANDS_NAME_UNIQUE
    UNIQUE (NAME);
    
ALTER TABLE CONNECTORS ADD CONSTRAINT CONNECTORS_TYOE_UNIQUE
    UNIQUE (TYPE);
ALTER TABLE CONNECTORS ADD CONSTRAINT CONNECTORS_AMP_VOLT
    CHECK (AMPERAGE>=0 AND VOLTAGE>=0 AND POWER>=0);

ALTER TABLE FAVOURITES ADD CONSTRAINT FAVOURITES_STATION_ID
    FOREIGN KEY(STATION_ID) REFERENCES STATIONS
    ON DELETE CASCADE;
ALTER TABLE FAVOURITES ADD CONSTRAINT FAVOURITES_USER_ID
    FOREIGN KEY(USER_ID) REFERENCES USERS
    ON DELETE CASCADE;
    
ALTER TABLE RATES ADD CONSTRAINT RATES_STATION_ID
    FOREIGN KEY (STATION_ID) REFERENCES STATIONS
    ON DELETE CASCADE;
ALTER TABLE RATES ADD CONSTRAINT RATES_USER_ID
    FOREIGN KEY (USER_ID) REFERENCES USERS
    ON DELETE CASCADE;
ALTER TABLE RATES ADD CONSTRAINT RATES_RATE_VALUE
    CHECK (RATE BETWEEN 0 AND 5);

ALTER TABLE STATIONS_CONNECTORS ADD CONSTRAINT STATIONS_CONNECTORS_STATION_ID
    FOREIGN KEY (STATION_ID) REFERENCES STATIONS
    ON DELETE CASCADE;
ALTER TABLE STATIONS_CONNECTORS ADD CONSTRAINT STATIONS_CONNECTORS_CONNECTOR_ID
    FOREIGN KEY (CONNECTOR_ID) REFERENCES CONNECTORS
    ON DELETE CASCADE;

ALTER TABLE RESERVATIONS ADD CONSTRAINT RESERVATIONS_TIME_UNIQUE
    UNIQUE(TIME, STATION_ID);
ALTER TABLE RESERVATIONS ADD CONSTRAINT RESERVATIONS_STATION_ID
    FOREIGN KEY(STATION_ID) REFERENCES STATIONS
    ON DELETE CASCADE;
ALTER TABLE RESERVATIONS ADD CONSTRAINT RESERVATIONS_USER_ID
    FOREIGN KEY(USER_ID) REFERENCES USERS
    ON DELETE CASCADE;