INSERT INTO STATIONS (CORDINATES, RATE, PRICE, STATUS) VALUES ('46.43070189690137, 30.718992567508057', 5, 50, 'WORK');
INSERT INTO STATIONS (CORDINATES, RATE, PRICE, STATUS) VALUES ('46.42899476392651, 30.72986905101524', 4.8, 50, 'WORK');
INSERT INTO STATIONS (CORDINATES, RATE, PRICE, STATUS) VALUES ('46.44638144300484, 30.758085794202678', 4.9, 50, 'OCCUPIED');
INSERT INTO STATIONS (CORDINATES, RATE, PRICE, STATUS) VALUES ('46.45715278963867, 30.75079677095989', 4.7, 50, 'ON_REPAIR');

INSERT INTO CONNECTORS (TYPE, AMPERAGE, VOLTAGE, POWER) VALUES ('Type 1 J1772', 32, 230, 7.4);
INSERT INTO CONNECTORS (TYPE, AMPERAGE, VOLTAGE, POWER) VALUES ('Type 2 (Mennekes)', 63, 400, 43);
INSERT INTO CONNECTORS (TYPE, AMPERAGE, VOLTAGE, POWER) VALUES ('CHAdeMO', 125, 600, 72.5);
INSERT INTO CONNECTORS (TYPE, AMPERAGE, VOLTAGE, POWER) VALUES ('CCS Combo', 200, 500, 100);

INSERT INTO STATIONS_CONNECTORS (STATION_ID, CONNECTOR_ID) VALUES (1, 2);
INSERT INTO STATIONS_CONNECTORS (STATION_ID, CONNECTOR_ID) VALUES (2, 4);
INSERT INTO STATIONS_CONNECTORS (STATION_ID, CONNECTOR_ID) VALUES (3, 1);
INSERT INTO STATIONS_CONNECTORS (STATION_ID, CONNECTOR_ID) VALUES (3, 2);
INSERT INTO STATIONS_CONNECTORS (STATION_ID, CONNECTOR_ID) VALUES (4, 1);

INSERT INTO BRANDS(NAME) VALUES ('Audi');
INSERT INTO BRANDS(NAME) VALUES ('Tesla');
INSERT INTO BRANDS(NAME) VALUES ('Jaguar');
INSERT INTO BRANDS(NAME) VALUES ('BMW');
INSERT INTO BRANDS(NAME) VALUES ('Nissan');

INSERT INTO AUTOS(BRAND_ID, MODEL, MAX_CHARGE, CONNECTOR_ID) VALUES (1, 'e-tron', 95, 2);
INSERT INTO AUTOS(BRAND_ID, MODEL, MAX_CHARGE, CONNECTOR_ID) VALUES (2, 'Model X', 100, 2);
INSERT INTO AUTOS(BRAND_ID, MODEL, MAX_CHARGE, CONNECTOR_ID) VALUES (3, 'i-Pace', 90, 4);
INSERT INTO AUTOS(BRAND_ID, MODEL, MAX_CHARGE, CONNECTOR_ID) VALUES (4, 'i3', 42.2, 1);
INSERT INTO AUTOS(BRAND_ID, MODEL, MAX_CHARGE, CONNECTOR_ID) VALUES (5, 'Leaf', 40, 2);
INSERT INTO AUTOS(BRAND_ID, MODEL, MAX_CHARGE, CONNECTOR_ID) VALUES (5, 'e-NV200', 40, 1);

INSERT INTO ROLES(NAME) VALUES ('USER');
INSERT INTO ROLES(NAME) VALUES ('ADMIN');

INSERT INTO USERS (LASTNAME, FIRSTNAME, MIDNAME, MAIL, PASSWORD, AUTO_ID, ROLE_ID) VALUES ('Гаврилюк', 'Алексей', 'Юрьевич', 'alekseygav2001@gmail.com', 'merzenniy', 1, 1);
INSERT INTO USERS (LASTNAME, FIRSTNAME, MIDNAME, MAIL, PASSWORD, AUTO_ID, ROLE_ID) VALUES ('Закиров', 'Олег', 'Александрович', 'zakirov2802@gmail.com', 'oleg3785', 4, 1);
INSERT INTO USERS (LASTNAME, FIRSTNAME, MIDNAME, MAIL, PASSWORD, AUTO_ID, ROLE_ID) VALUES ('Добриогло', 'Константин', 'Игоревич', 'mrkross35@gmail.com', 'vatbane', 3, 1);
INSERT INTO USERS (LASTNAME, FIRSTNAME, MIDNAME, MAIL, PASSWORD, AUTO_ID, ROLE_ID) VALUES ('Деревенча', 'Владимир', 'Викторович', 'derevencha@gmail.com', 'gelios93', 6, 1);
INSERT INTO USERS (LASTNAME, FIRSTNAME, MIDNAME, MAIL, PASSWORD, AUTO_ID, ROLE_ID) VALUES ('Мясникова', 'Екатерина', 'Алексеевна', 'katya.miasnikova@gmail.com', 'green123', 2, 1);
INSERT INTO USERS (LASTNAME, FIRSTNAME, MIDNAME, MAIL, PASSWORD, AUTO_ID, ROLE_ID) VALUES ('Расстёба', 'Владислав', 'Владимирович', 'vlad_r@gmail.com', 'vlad9124', 5, 1);

INSERT INTO FAVOURITES(STATION_ID, USER_ID) VALUES (1, 1);
INSERT INTO FAVOURITES(STATION_ID, USER_ID) VALUES (1, 5);
INSERT INTO FAVOURITES(STATION_ID, USER_ID) VALUES (2, 3);
INSERT INTO FAVOURITES(STATION_ID, USER_ID) VALUES (3, 4);
INSERT INTO FAVOURITES(STATION_ID, USER_ID) VALUES (4, 2);

INSERT INTO RATES (STATION_ID, USER_ID, RATE, COMMENTARY) VALUES (1, 1, 5, 'Всё круто!');
INSERT INTO RATES (STATION_ID, USER_ID, RATE, COMMENTARY) VALUES (2, 1, 4, '');
INSERT INTO RATES (STATION_ID, USER_ID, RATE, COMMENTARY) VALUES (3, 2, 5, '');
INSERT INTO RATES (STATION_ID, USER_ID, RATE, COMMENTARY) VALUES (4, 3, 4, '');


INSERT INTO RESERVATIONS (TIME, TIME_END, CODE, USER_ID, STATION_ID, CREATED_AT) VALUES (TO_TIMESTAMP('10-10-2021 10:00:00'), ('10-10-2021 12:00:00'), '14515', 1, 1, ('10-10-2021'));
INSERT INTO RESERVATIONS (TIME, TIME_END, CODE, USER_ID, STATION_ID, CREATED_AT) VALUES (TO_TIMESTAMP('10-10-2021 14:00:00'), ('10-10-2021 15:00:00'), '53153', 2, 2, ('10-10-2021'));
INSERT INTO RESERVATIONS (TIME, TIME_END, CODE, USER_ID, STATION_ID, CREATED_AT) VALUES (TO_TIMESTAMP('11-10-2021 10:00:00'), ('11-10-2021 12:00:00'), '25253', 3, 3, ('10-10-2021'));
INSERT INTO RESERVATIONS (TIME, TIME_END, CODE, USER_ID, STATION_ID, CREATED_AT) VALUES (TO_TIMESTAMP('12-12-2021 10:00:00'), ('12-12-2021 14:00:00'), '53252', 4, 4, ('11-10-2021'));
INSERT INTO RESERVATIONS (TIME, TIME_END, CODE, USER_ID, STATION_ID, CREATED_AT) VALUES (TO_TIMESTAMP('12-01-2022 10:00:00'), ('12-01-2022 14:00:00'), '53255', 4, 4, ('11-01-2022'));
INSERT INTO RESERVATIONS (TIME, TIME_END, CODE, USER_ID, STATION_ID, CREATED_AT) VALUES (TO_TIMESTAMP('15-01-2022 10:00:00'), ('15-01-2022 14:00:00'), '53255', 4, 3, ('14-01-2022'));


INSERT INTO STATISTICS(STATISTIC_ID, URI, OPERATION_TYPE, CREATED_AT, BUSINESS_OPERATION_NAME) VALUES(STATISTICS_SEQUENCE.NEXTVAL, '/', 'GET', '05.03.2019', 'main page');
INSERT INTO STATISTICS(STATISTIC_ID, URI, OPERATION_TYPE, CREATED_AT, BUSINESS_OPERATION_NAME) VALUES(STATISTICS_SEQUENCE.NEXTVAL, '/', 'GET', '03.01.2020', 'main page');
INSERT INTO STATISTICS(STATISTIC_ID, URI, OPERATION_TYPE, CREATED_AT, BUSINESS_OPERATION_NAME) VALUES(STATISTICS_SEQUENCE.NEXTVAL, '/', 'GET', '04.02.2020', 'main page');
INSERT INTO STATISTICS(STATISTIC_ID, URI, OPERATION_TYPE, CREATED_AT, BUSINESS_OPERATION_NAME) VALUES(STATISTICS_SEQUENCE.NEXTVAL, '/login', 'GET', '03.01.2021', 'login page');
INSERT INTO STATISTICS(STATISTIC_ID, URI, OPERATION_TYPE, CREATED_AT, BUSINESS_OPERATION_NAME) VALUES(STATISTICS_SEQUENCE.NEXTVAL, '/login', 'GET', '04.01.2021', 'login page');
INSERT INTO STATISTICS(STATISTIC_ID, URI, OPERATION_TYPE, CREATED_AT, BUSINESS_OPERATION_NAME) VALUES(STATISTICS_SEQUENCE.NEXTVAL, '/login', 'GET', '05.10.2021', 'login page');
INSERT INTO STATISTICS(STATISTIC_ID, URI, OPERATION_TYPE, CREATED_AT, BUSINESS_OPERATION_NAME) VALUES(STATISTICS_SEQUENCE.NEXTVAL, '/user/profile', 'GET', '03.01.2021', 'user profile page');
INSERT INTO STATISTICS(STATISTIC_ID, URI, OPERATION_TYPE, CREATED_AT, BUSINESS_OPERATION_NAME) VALUES(STATISTICS_SEQUENCE.NEXTVAL, '/', 'GET', '03.01.2021', 'main page');
INSERT INTO STATISTICS(STATISTIC_ID, URI, OPERATION_TYPE, CREATED_AT, BUSINESS_OPERATION_NAME) VALUES(STATISTICS_SEQUENCE.NEXTVAL, '/registration', 'GET', '05.10.2022', 'registration page');
INSERT INTO STATISTICS(STATISTIC_ID, URI, OPERATION_TYPE, CREATED_AT, BUSINESS_OPERATION_NAME) VALUES(STATISTICS_SEQUENCE.NEXTVAL, '/registration', 'GET', '07.01.2022', 'registration page');
INSERT INTO STATISTICS(STATISTIC_ID, URI, OPERATION_TYPE, CREATED_AT, BUSINESS_OPERATION_NAME) VALUES(STATISTICS_SEQUENCE.NEXTVAL, '/registration', 'GET', '09.01.2022', 'registration page');
INSERT INTO STATISTICS(STATISTIC_ID, URI, OPERATION_TYPE, CREATED_AT, BUSINESS_OPERATION_NAME) VALUES(STATISTICS_SEQUENCE.NEXTVAL, '/registration', 'GET', '04.02.2022', 'registration page');
INSERT INTO STATISTICS(STATISTIC_ID, URI, OPERATION_TYPE, CREATED_AT, BUSINESS_OPERATION_NAME) VALUES(STATISTICS_SEQUENCE.NEXTVAL, '/registration', 'GET', '08.02.2022', 'registration page');
INSERT INTO STATISTICS(STATISTIC_ID, URI, OPERATION_TYPE, CREATED_AT, BUSINESS_OPERATION_NAME) VALUES(STATISTICS_SEQUENCE.NEXTVAL, '/', 'GET', '03.01.2022', 'main page');
INSERT INTO STATISTICS(STATISTIC_ID, URI, OPERATION_TYPE, CREATED_AT, BUSINESS_OPERATION_NAME) VALUES(STATISTICS_SEQUENCE.NEXTVAL, '/', 'GET', '02.01.2022', 'main page');
INSERT INTO STATISTICS(STATISTIC_ID, URI, OPERATION_TYPE, CREATED_AT, BUSINESS_OPERATION_NAME) VALUES(STATISTICS_SEQUENCE.NEXTVAL, '/profile', 'GET', '01.01.2022', 'user profile page');
INSERT INTO STATISTICS(STATISTIC_ID, URI, OPERATION_TYPE, CREATED_AT, BUSINESS_OPERATION_NAME) VALUES(STATISTICS_SEQUENCE.NEXTVAL, '/profile', 'GET', '01.02.2022', 'user profile page');